services:
  - type: static_site
    name: angular-honey-app
    buildCommand: npm install && npm run build
    staticPublishPath: dist/app/browser
    routes:
      - path: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
