services:
  - type: static_site
    name: angular-honey-app
    buildCommand: npm install && npm run build
    staticPublishPath: dist/app/browser
    envVars:
      - key: NODE_ENV
        value: production
